@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
Person(policyholder, "Policyholder")
Person(agent, "Agent")
Person(staff, "Company Staff")
System_Boundary(imic, "IMIC") {
  System(web, "Internet Site", "Policyholder & Agent Portal")
  System(intranet, "Intranet Site", "Company Backend App")
}
Rel(policyholder, web, "Views details; claims status")
Rel(agent, web, "Enters policies & claims")
Rel(staff, intranet, "Approves/Rejects policies & claims")
@enduml
